### ISSUE TITLE
componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by slimandslam** [Codebrahma/react-notifications-menu#9]
Using React 17, I get this warning from your component (version 1.0.5)

```
import Notifications from "react-notifications-menu";
...
...
...
<Notifications
                   data={[ { image: newuser,
                    message: 'You have achieved advanced status', detailPage: '/stats', }, ]}
                    height='100px'
                    width='300px'
                    header={ { title: 'Notifications', option: { text: '', onClick: () => {} } } }
                    />
```

The warning:

react-dom.development.js:67 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.
* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
**Please update the following components: Notifications**
printWarning @ react-dom.development.js:67

**Comment by ashwinKumar0505** [comment]
This issue has been resolved.
